name: main

on: [ push ]

jobs:

  unit:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2

      - run: |
          npm ci
          npm run test:unit

  deliver_docker:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: xvlcw
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            xvlcw/rui-fe:latest
            xvlcw/rui-fe:0
            xvlcw/rui-fe:0.14
            xvlcw/rui-fe:0.14.0

  e2e:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2

      - run: |
          npm ci
          npm run test:e2e:headless
      
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          path: tests/e2e/screenshots/
