on: [ push ]

jobs:

  unit:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2

      - run: |
          npm ci
          npm run test:unit

  e2e:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout from GitHub
        uses: actions/checkout@v2

      - name: Start backend
        run: docker run --publish "5000:5000" --detach xvlcw/rui-be:0.9.0

      - name: Wait for backend
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: 'http://localhost:5000/'

      - name: Run e2e tests
        run: |
          npm ci
          npm run test:e2e:headless

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          path: tests/e2e/screenshots/
